[package]
name = "tauri-plugin-device-info"
version = "1.0.0"
authors = ["edisdev <edisdev14@gmail.com>"]
description = "A Tauri plugin to access device information."
license = "MIT"
repository = "https://github.com/edisdev/tauri-plugin-device-info"
homepage = "https://github.com/edisdev/tauri-plugin-device-info"
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/docs", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-device-info"

[dependencies]
tauri = { version = "2.7.0" }
serde = "1.0"
thiserror = "2"
sysinfo = "0.34.2"
local-ip-address = "0.6.9"
default-net = "0.22.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winbase", "winnt"] }
wmi = "0.13"
battery = "0.7.8"

[target.'cfg(target_os = "macos")'.dependencies]
battery = "0.7.8"
serde_json = "1.0"
core-graphics = "0.25.0"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
battery = "0.7.8"

[build-dependencies]
tauri-plugin = { version = "2.5.2", features = ["build"] }
